### ISSUE TITLE
Требуется рефакторинг

### ISSUE THREAD

**Issue by E1izabeth** [arseniypopugay/BegginersLab#3]
В задании 8 следует разделить логику, отвечающую за ввод-вывод от прикладной логики программы. Изучите принцип единственной ответственности и проведите рефакторинг.

**Comment by arseniypopugay** [comment]
Сделано (надеюсь)

**Comment by E1izabeth** [comment]
Вопрос: текстовое сообщение, которое вы возвращаете относится к внутренней логике или к внутренней логике относится признак результата?

**Comment by arseniypopugay** [comment]
Возможно, было бы логичнее использовать "кодовое число выполнения результата", тогда программа стала бы более масштабируемая для других языков. Но почему бы не использовать вместо этого строки и не выводить их как результат работы?) 
Поэтому, к внутренней логике я бы отнес сообщение как признак.

**Comment by E1izabeth** [comment]
И тогда если я хочу поменять сообщение, которое выводится пользователю, мне нужно идти и менять его в методе, отвечающем за логику, а не в ответственном за общение с пользователем. А если у меня клиент-серверное приложение, с, например, двумя разными реализациями клиентской стороны, то мне, чтобы изменить сообщение-признак результата, нужно пойти в код сервера и поменять отдаваемое сообщение во внутрунней логике на сервере. А что делать, если я в двух реализациях клиента хочу отдавать разные сообщения? Парсить отдаваемое сервером сообщение и изменять его на своё? Насколько используемый подход приемлем в более сложных ситуациях и насколько корректно вкладывать во внутреннюю логику знание о том, какое сообщение будет выведено пользователю?
(Предлагаю сначала пофиксить остальные аспекты, а потом вернуться и подумать над этим)

**Comment by E1izabeth** [comment]
To be fixed in lab2
